public class CPUTimeLimit{
    public static void docheck(){
    	Integer count=0;
        Integer lpsize=66000;
        Integer i1=0;
        Integer ii=0;
        Integer iii=0;
        for(Integer i=0;i<lpsize;i++){
            count++;
            count++;
            i1=Count++;
            ii=Count++;
            iii=Count++;
            iii=Count++;
        system.debug('CPU Time in Loop'+limits.getCPUTime());
        }
        system.debug('CPU Time **Final**'+limits.getCPUTime());
    }
}