public class MyCLsOptum{
/*
dhr__Inquiry__c inq = [select id,dhr__Email__c from dhr__Inquiry__c where id='a0w90000006FnnqAAC'];
Contact con = [select id,email from COntact where email!=null limit 1];
List<Messaging.SingleEmailMessage> msgList= new List<Messaging.SingleEmailMessage>();
Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
msg.setTemplateId( [select id from EmailTemplate where DeveloperName='Optum_Email_Test'].id );
msg.setWhatId(inq.id);
msg.setTargetObjectId(con.id);
msg.setToAddresses(new List<String>{'babu_kodi@optum.com'});
msgList.add(msg);
Messaging.sendEmail(msgList); // Dummy email send


*/
}