Public class RefundResult {
    public String transaction_id;
    public String status;
    public String type;
    public String currencyIsoCode;
    public String amount;
    public String merchantAccountId;
    public String refundedTransactionId;
    public String processorResponseCode;
    public String processorResponseText;
    public String paymentInstrumentType;
    public String DonationDate;
    public String Timezone_type;
    public String Timezone;
}