@isTest
Private class StoreProductStockUpdateTest{
    /*private static testMethod void unitTest(){
        List<csfs_Store_Product__c> strprdLst = new List<csfs_Store_Product__c>();
        csfs_Store_Product__c strprd = new csfs_Store_Product__c();
        strprd.name='Test Store Product';
        strprd.SKU__c='123';
        
        strprdLst.add(strprd);
        insert strprdLst;
        
        List<SAP_Stock__c> spskLst = new List<SAP_Stock__c>();
        SAP_Stock__c spsk = new SAP_Stock__c();
        spsk.name='Test';
        spsk.Centro__c='111';
        spsk.N_mero_do_Material__c='123';
        spsk.Faixa_de_Vida_til__c='0';
        spsk.Estoque_avaliado_de_utiliza_o_livre__c=100;
        
        spskLst.add(spsk);
        
        SAP_Stock__c spsk1 = new SAP_Stock__c();
        spsk1.name='Test';
        spsk1.Centro__c='111';
        spsk1.N_mero_do_Material__c='123';
        spsk1.Faixa_de_Vida_til__c='01';
        spsk1.Estoque_avaliado_de_utiliza_o_livre__c=101;
        
        spskLst.add(spsk1);
        
        SAP_Stock__c spsk2 = new SAP_Stock__c();
        spsk2.name='Test';
        spsk2.Centro__c='111';
        spsk2.N_mero_do_Material__c='123';
        spsk2.Faixa_de_Vida_til__c='02';
        spsk2.Estoque_avaliado_de_utiliza_o_livre__c=102;
        
        spskLst.add(spsk2);
        
        SAP_Stock__c spsk3 = new SAP_Stock__c();
        spsk3.name='Test';
        spsk3.Centro__c='111';
        spsk3.N_mero_do_Material__c='123';
        spsk3.Faixa_de_Vida_til__c='00';
        spsk3.Estoque_avaliado_de_utiliza_o_livre__c=103;
        
        spskLst.add(spsk3);
        
        insert spskLst;
        
        StoreProductStockUpdate.updateSPStock('111',strprdLst);
    }*/
}