@isTest
Private class UsualMixFlagForStoreProductTest{
    /*private static testMethod void unitTest(){
       List<csfs_Store_Product__c> strprdLst = new List<csfs_Store_Product__c>();
       csfs_Store_Product__c strprd = new csfs_Store_Product__c();
       strprd.name='Test Store Product';
       strprd.SKU__c='123';
        
       strprdLst.add(strprd);
       insert strprdLst;
       
       Hist_rico_de_Vendas__c hrdv = new Hist_rico_de_Vendas__c();
       hrdv.Material__c='123';
       Integer mnth = system.today().month()-1;
       String mnthStr = String.valueOf(mnth);
       mnthStr = mnthStr.leftPad(2,'0');
       hrdv.Ano_civil_m_s__c='2017'+mnthStr;
       
       insert hrdv;
       
       UsualMixFlagForStoreProduct.UpdateUsualFlag(strprdLst); 
    }*/
}